name: Remote update execution
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Run a command
        run: echo Test

  deploy:
    name: Build
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sh /srv/www/staging.noomna.com/htdocs/sleep-stories-frontend/release.sh

  deploy_for_staging:
    name: Deploy for staging
#    if: github.event_name == 'push' && github.event.ref == 'refs/heads/development'
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Test environment
        run: |
          echo Staging
          echo '${secrets.SSH_USER}'